import os

DATABASE_NAME="cometdb"
DATABASE_USER="postgres"
DATABASE_PASSWORD=os.environ["PostregrePassword"]
DATABASE_HOST="127.0.0.1"
DATABASE_PORT="5432"

SUPPORT_THRESHOLD=20
NULL_THRESHOLD=30


CONNECTION_CONFIG_DICT={
    'database':DATABASE_NAME, 
    'user':DATABASE_USER, 
    'password':DATABASE_PASSWORD, 
    'host':DATABASE_HOST, 
    'port': DATABASE_PORT
}

DATABASE_ENGINE=f"""postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:{DATABASE_PORT}/{DATABASE_NAME}"""
