import os
import glob
import pandas as pd
os.chdir(os.getcwd()+"/Data/wide_property_table_csv")
# cols="s,http___purl_org_goodrelations_offers,http___schema_org_wordCount,http___xmlns_com_foaf_homepage,http___purl_org_ontology_mo_producer,http___schema_org_actor,http___schema_org_numberOfPages,http___purl_org_ontology_mo_movement,http___schema_org_birthDate,http___db_uwaterloo_ca__galuc_wsdbm_purchaseDate,http___schema_org_producer,http___purl_org_stuff_rev_hasReview,http___schema_org_isbn,http___purl_org_ontology_mo_performer,http___purl_org_goodrelations_name,http___schema_org_director,http___purl_org_ontology_mo_record_number,http___schema_org_jobTitle,http___schema_org_openingHours,http___schema_org_language,http___schema_org_publisher,http___purl_org_dc_terms_Location,http___www_geonames_org_ontology_parentCountry,http___schema_org_aggregateRating,http___www_w3_org_1999_02_22_rdf_syntax_ns_type,http___schema_org_employee,http___purl_org_goodrelations_price,http___schema_org_award,http___schema_org_duration,http___purl_org_goodrelations_description,http___schema_org_faxNumber,http___schema_org_expires,http___schema_org_eligibleQuantity,http___purl_org_stuff_rev_title,http___db_uwaterloo_ca__galuc_wsdbm_composer,http___db_uwaterloo_ca__galuc_wsdbm_gender,http___ogp_me_ns_title,http___schema_org_editor,http___purl_org_stuff_rev_rating,http___purl_org_goodrelations_includes,http___db_uwaterloo_ca__galuc_wsdbm_hits,http___schema_org_trailer,http___schema_org_keywords,http___purl_org_goodrelations_validThrough,http___schema_org_email,http___schema_org_priceValidUntil,http___purl_org_ontology_mo_performed_in,http___schema_org_nationality,http___purl_org_stuff_rev_reviewer,http___schema_org_text,http___db_uwaterloo_ca__galuc_wsdbm_makesPurchase,http___schema_org_description,http___schema_org_bookEdition,http___db_uwaterloo_ca__galuc_wsdbm_userId,http___purl_org_ontology_mo_opus,http___schema_org_telephone,http___schema_org_contentSize,http___xmlns_com_foaf_familyName,http___purl_org_goodrelations_serialNumber,http___purl_org_ontology_mo_release,http___schema_org_datePublished,http___purl_org_stuff_rev_totalVotes,http___db_uwaterloo_ca__galuc_wsdbm_hasGenre,http___schema_org_printPage,http___purl_org_stuff_rev_text,http___purl_org_ontology_mo_conductor,http___ogp_me_ns_tag,http___schema_org_eligibleRegion,http___xmlns_com_foaf_givenName,http___db_uwaterloo_ca__galuc_wsdbm_follows,http___schema_org_paymentAccepted,http___xmlns_com_foaf_age,http___purl_org_ontology_mo_artist,http___schema_org_printSection,http___schema_org_author,http___purl_org_goodrelations_validFrom,http___schema_org_printColumn,http___schema_org_caption,http___schema_org_url,http___db_uwaterloo_ca__galuc_wsdbm_likes,http___schema_org_contentRating,http___schema_org_printEdition,http___db_uwaterloo_ca__galuc_wsdbm_purchaseFor,http___schema_org_legalName,http___db_uwaterloo_ca__galuc_wsdbm_subscribes,http___db_uwaterloo_ca__galuc_wsdbm_friendOf,http___schema_org_contactPoint"
# headers=cols.split(',')
# print(headers)
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

sum=0
for file in all_filenames:
    
    for row in open(file):
        sum+= 1
 #printing the result
print("Number of lines present:-", sum)

